name: Deploy

on:
  push:
    branches: [ main ]

env:
    VERSION: 1.0.${{ github.run_attempt }}-${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release
      
    - name: Zip
      run: tar -cvf SoulWorker_ResStructureExtractor_${{ env.VERSION }}.zip -C SoulWorker.ResStructureExtractor.Cli/bin/Release/net7.0/publish/ *
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: SoulWorker_ResStructureExtractor_${{ env.VERSION }}.zip
        tag_name: ${{ env.VERSION }}
        generate_release_notes: true
